import { TodoType } from "./types"

export const INITIAL_TODOS: TodoType[] = [
  {
    id: 1,
    title: "Buy groceries",
    completed: false,
    disabled: false,
    prefixed: false,
  },
  {
    id: 2,
    title: "Finish project documentation",
    completed: true,
    disabled: false,
    prefixed: false,
  },
  {
    id: 3,
    title: "Schedule dentist appointment",
    completed: false,
    disabled: false,
    prefixed: false,
  },
  {
    id: 4,
    title: "Clean the house",
    completed: false,
    disabled: false,
    prefixed: false,
  },
  {
    id: 5,
    title: "Pay monthly bills",
    completed: true,
    disabled: false,
    prefixed: false,
  },
  {
    id: 6,
    title: "Go to the gym",
    completed: false,
    disabled: false,
    prefixed: false,
  },
  {
    id: 7,
    title: "Read a book",
    completed: false,
    disabled: false,
    prefixed: false,
  },
  {
    id: 8,
    title: "Call mom",
    completed: true,
    disabled: false,
    prefixed: false,
  },
  {
    id: 9,
    title: "Update resume",
    completed: false,
    disabled: false,
    prefixed: false,
  },
  {
    id: 10,
    title: "Plan weekend trip",
    completed: false,
    disabled: false,
    prefixed: false,
  },
  {
    id: 11,
    title: "Fix broken laptop",
    completed: true,
    disabled: false,
    prefixed: false,
  },
  {
    id: 12,
    title: "Learn new programming language",
    completed: false,
    disabled: false,
    prefixed: false,
  },
  {
    id: 13,
    title: "Organize photos",
    completed: false,
    disabled: false,
    prefixed: false,
  },
  {
    id: 14,
    title: "Buy birthday gift",
    completed: true,
    disabled: false,
    prefixed: false,
  },
  {
    id: 15,
    title: "Practice guitar",
    completed: false,
    disabled: false,
    prefixed: false,
  },
  {
    id: 16,
    title: "Write blog post",
    completed: false,
    disabled: false,
    prefixed: false,
  },
]
